### ISSUE TITLE
set separate background color for dark mode 

### ISSUE THREAD

**Issue by suntudo** [gabrielcsapo/docusaurus-plugin-image-zoom#1]
Hi there, thanks for this great plugin. Super useful. However, it seems that it's only possible to set a single `background` color (unless I'm missing something). The default white background color doesn't work great with dark mode. I was able to change it to a grey with transparency, which works better, but I was wondering about possibly setting two separate `background` colors. Is that possible?`

**Comment by gabrielcsapo** [comment]
This is a good question, let me double-check how to best do this.

**Comment by gabrielcsapo** [comment]
https://github.com/gabrielcsapo/docusaurus-plugin-image-zoom/commit/c481cd85f338663d4bb17e9bd3015ad4f64f9c95 contains the fix to allow you to have your own custom dark and light theme

This is what it looks like.
![dark-mode-overlay-toggle](https://user-images.githubusercontent.com/1854811/135197385-ceeb4bdc-f797-4904-a984-99e14afbe489.gif)

**Comment by suntudo** [comment]
Awesome. Thanks so much!
