### ISSUE TITLE
version 0.1.3 breaks build

### ISSUE THREAD

**Issue by noobinthisgame** [gabrielcsapo/docusaurus-plugin-image-zoom#21]
Installing the new version in a docsaurus project breaks the build as no source files are delivered in the package: 

My node_modules:
![image](https://user-images.githubusercontent.com/21695702/232448775-c5672757-52a5-40e5-9dc2-2c2f9260df8b.png)

I see there is already a commit fixing this. Could we get a release soon?

**Comment by gabrielcsapo** [comment]
Cc @scalvert

**Comment by scalvert** [comment]
I'd already released 0.1.14 to fix that issue. Please upgrade.
