### ISSUE TITLE
Warning: Workspaces can only be enabled in private projects

### ISSUE THREAD

**Issue by norosa** [gabrielcsapo/docusaurus-plugin-image-zoom#5]
Thanks for writing this plugin! It works great, even when used in combination with [@docusaurus/plugin-ideal-image][ideal-zoom].

However, when installing, I see:

```
 $ yarn add docusaurus-plugin-image-zoom
yarn add v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
success Saved lockfile.
warning Workspaces can only be enabled in private projects.
success Saved 2 new dependencies.
info Direct dependencies
└─ docusaurus-plugin-image-zoom@0.1.0
info All dependencies
├─ docusaurus-plugin-image-zoom@0.1.0
└─ medium-zoom@1.0.6
Done in 4.64s.
```

Could this be to blame:

https://github.com/gabrielcsapo/docusaurus-plugin-image-zoom/blob/c2c1155080dc847e542a039d11aba5de3e05774b/package.json#L23-L25

[ideal-zoom]: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image

**Comment by gabrielcsapo** [comment]
Thanks @norosa, fixing this now. We have no reason to install it as a workspace and publish it as a workspace.

**Comment by gabrielcsapo** [comment]
should be fixed in https://github.com/gabrielcsapo/docusaurus-plugin-image-zoom/commit/7fc492c1aec46ffeb7562d5e736197f9fe2af195 [0.1.1]! Thank you @norosa
